#!/bin/bash

# store current script directories
SCRIPT_DIR=`dirname $0`

# configure python environment
export PYTHONIOENCODING=utf-8
PYTHONPATH=$SNAP/usr/lib/python3/site-packages:$PYTHONPATH
PYTHONPATH=$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
PYTHONPATH=$SNAP/lib/python3.8/site-packages:$PYTHONPATH
export PYTHONPATH
export PYTHON=$SNAP/usr/bin/python3.8

# ensure curtin points at PYTHON
export PY3OR2_PYTHON=$PYTHON

# set the PATH so subiquity finds curtin
export PATH=$SNAP/bin:$PATH

# base directory for subiquity to locate resources
export SUBIQUITY_ROOT=$SNAP/bin/subiquity

# run subiquity server
cd $SCRIPT_DIR/subiquity

args=()
if grep -qv "experimental-autoinstall" /proc/cmdline; then
    # autoinstall is explicitly disabled until UI support is present.
    # Remove this autoinstall argument when that is resolved.
    args+=(--autoinstall="")
fi

$PYTHON -m subiquity.cmd.server "${args[@]}"
