version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
        interval: "daily"
        time: "03:00"
    target-branch: "main"
    commit-message:
      prefix: "chore"
      include: "scope"
