include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.mocks.dart"
    - "**/l10n/*.dart"

linter:
  rules:
    constant_identifier_names: false
    lines_longer_than_80_chars: false
    prefer_const_constructors: false # TODO: enable
    public_member_api_docs: false
    sort_pub_dependencies: true

    # TODO: the following rules were temporarily disabled to make it easier to
    # transition to flutter_lints 2.0 that has these new rules enabled by default
    depend_on_referenced_packages: false
    library_private_types_in_public_api: false
    sort_child_properties_last: false
    use_build_context_synchronously: false
