include: package:effective_dart/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.mocks.dart"
    - "**/l10n/*.dart"

linter:
  rules:
    constant_identifier_names: false
    lines_longer_than_80_chars: false
    # prefer_const_constructors: true
    public_member_api_docs: false
    sort_pub_dependencies: true
    use_setters_to_change_properties: false
