name: ubuntu_desktop_installer

packages:
  - packages/**

ignore:
  - synthetic_package

environment:
  sdk: '>=2.12.0 <3.0.0'

scripts:
  # analyze all packages
  analyze: >
    melos exec -c 1 -- \
      flutter analyze --no-fatal-infos .

  # collect coverage information for all packages
  coverage: >
    melos exec -c 1 --fail-fast --dir-exists=test -- \
      flutter test --coverage && melos run coverage:cleanup

  # cleanup generated files from coverage
  coverage:cleanup: >
    melos exec --file-exists=coverage/lcov.info -- \
      lcov --remove coverage/lcov.info '**/*.g.dart' '**/*.freezed.dart' -o coverage/lcov.info

  # format all packages
  format: >
    find . -name '*.dart' \
      ! -name '*.g.dart' \
      ! -name '*.freezed.dart' \
      ! -path '*/l10n/*' \
      ! -path "*/.*/*" \
      | xargs flutter format --set-exit-if-changed

  # run build_runner to generate code in all packages
  generate: >
    melos exec -c 1 --fail-fast --depends-on="build_runner" -- \
      dart run build_runner build --delete-conflicting-outputs

  # run gen-l10n to generate localizations in all packages
  gen-l10n:
    melos exec -c 1 --fail-fast --file-exists="lib/l10n.dart" -- \
     flutter gen-l10n

  # run integration tests in all packages
  integration_test: >
    melos exec -c 1 --fail-fast --dir-exists=integration_test -- \
      flutter test integration_test

  # run tests in all packages
  test: >
    melos exec -c 1 --fail-fast --dir-exists=test -- \
      flutter test
