#!/bin/sh
set -e

target=/target
source_nm=/etc/NetworkManager/system-connections
target_nm=$target/$source_nm

if test -d $source_nm && test -d $target_nm; then
    cp -anr $source_nm/. $target_nm
fi
