name: timezone_map
description: Timezone map widget.
publish_to: 'none'

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  file: ^6.1.2
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  latlong2: ^0.8.1
  mockito: 5.1.0
  path: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
