name: pwquality
description: Password quality checking and generating random passwords.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypt: ^4.0.1
  ffi: ^1.1.2
  meta: ^1.7.0

dev_dependencies:
  ffigen: ^3.0.0
  lints: ^1.0.1
  test: ^1.16.0
