include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    constant_identifier_names: false
    lines_longer_than_80_chars: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
