// Mocks generated by Mockito 5.0.14 from annotations
// in ubuntu_desktop_installer/test/configure_active_directory_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;
import 'dart:ui' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ubuntu_desktop_installer/pages/configure_active_directory/configure_active_directory_model.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ConfigureActiveDirectoryModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigureActiveDirectoryModel extends _i1.Mock
    implements _i2.ConfigureActiveDirectoryModel {
  MockConfigureActiveDirectoryModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get domain =>
      (super.noSuchMethod(Invocation.getter(#domain), returnValue: '')
          as String);
  @override
  set domain(String? value) =>
      super.noSuchMethod(Invocation.setter(#domain, value),
          returnValueForMissingStub: null);
  @override
  String get admin =>
      (super.noSuchMethod(Invocation.getter(#admin), returnValue: '')
          as String);
  @override
  set admin(String? value) =>
      super.noSuchMethod(Invocation.setter(#admin, value),
          returnValueForMissingStub: null);
  @override
  String get password =>
      (super.noSuchMethod(Invocation.getter(#password), returnValue: '')
          as String);
  @override
  set password(String? value) =>
      super.noSuchMethod(Invocation.setter(#password, value),
          returnValueForMissingStub: null);
  @override
  bool get isValid =>
      (super.noSuchMethod(Invocation.getter(#isValid), returnValue: false)
          as bool);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i3.Future<void> testConnection() =>
      (super.noSuchMethod(Invocation.method(#testConnection, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> load() => (super.noSuchMethod(Invocation.method(#load, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> save() => (super.noSuchMethod(Invocation.method(#save, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  void addListener(_i4.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i4.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
