// Mocks generated by Mockito 5.0.14 from annotations
// in ubuntu_desktop_installer/test/turn_off_bitlocker_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ubuntu_desktop_installer/pages/turn_off_bitlocker/turn_off_bitlocker_model.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [TurnOffBitLockerModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockTurnOffBitLockerModel extends _i1.Mock
    implements _i2.TurnOffBitLockerModel {
  MockTurnOffBitLockerModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> reboot() =>
      (super.noSuchMethod(Invocation.method(#reboot, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}
