name: udev
description: >-
  Provides APIs to introspect and enumerate devices on the local system.
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ffi: ^2.0.1
  meta: ^1.7.0

dev_dependencies:
  ffigen: ^6.0.1
  flutter_lints: ^2.0.0
  test: ^1.17.7
