name: udev
description: >-
  Provides APIs to introspect and enumerate devices on the local system.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0

dev_dependencies:
  ffigen: ^2.4.2
  flutter_lints: ^1.0.0
  test: ^1.17.7
