name: ubuntu_utils
description: Shared library for Ubuntu wizards.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  args: ^2.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.8.0
  path: ^1.8.0
  safe_change_notifier: ^0.2.0
  ubuntu_localizations: ^0.2.0
  ubuntu_logger: ^0.0.3
  ubuntu_service: ^0.2.2
  url_launcher: ^6.1.0
  yaru_colors: ^0.1.6

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: 5.4.2
  plugin_platform_interface: ^2.1.2
  url_launcher_platform_interface: ^2.0.5
