#!/usr/bin/env python3

import subprocess
from ruamel.yaml import YAML

# update subiquity_client to remote HEAD
submodule = 'packages/subiquity_client'
cmd = 'git submodule update --init --remote ' + submodule
subprocess.check_call(cmd.split(' '))
# update subiquity_client's submodules
cmd = 'git submodule update --init --recursive ' + submodule
subprocess.check_call(cmd.split(' '))

yaml = YAML()
yaml.default_flow_style = False
yaml.pure = True
yaml.indent(mapping=2, sequence=2, offset=2)

with open('snap/snapcraft.yaml', 'r') as fp:
    udi_data = yaml.load(fp)

with open('packages/subiquity_client/subiquity/snapcraft.yaml', 'r') as fp:
    subiquity_data = yaml.load(fp)

for part in ('probert', 'curtin'):
    udi_data['parts'][part]['source-commit'] = \
        subiquity_data['parts'][part]['source-commit']

with open('snap/snapcraft.yaml', 'w') as fp:
    yaml.dump(udi_data, fp)
