name: ubuntu_init
description: Ubuntu Init
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  collection: ^1.17.0
  dbus: ^0.7.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  gsettings: ^0.2.7
  meta: ^1.7.0
  stdlibc: ^0.1.0
  ubuntu_localizations: ^0.3.3
  ubuntu_provision:
    path: ../ubuntu_provision
  ubuntu_session: ^0.0.4
  ubuntu_wizard:
    path: ../ubuntu_wizard
  xdg_locale: ^0.0.1
  yaru_widgets: ^2.5.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: 5.4.2
  ubuntu_test: ^0.1.0-0
  yaru_test: ^0.1.1

flutter:
  assets:
    - assets/
    - assets/kbds/
