name: ubuntu_welcome
description: Ubuntu Welcome
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  handy_window: ^0.3.0
  timezone_map:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/timezone_map
      ref: 5af6896c75b5ab8f78b93f7f358836a8c4c7857f
  ubuntu_init:
    path: ../ubuntu_init
  ubuntu_localizations: ^0.3.3
  ubuntu_logger: ^0.0.3
  ubuntu_provision:
    path: ../ubuntu_provision
  ubuntu_service: ^0.2.0
  ubuntu_utils:
    path: ../ubuntu_utils
  ubuntu_wizard:
    path: ../ubuntu_wizard
  yaru_widgets: ^2.5.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
