name: ubuntu_welcome
description: Ubuntu Welcome
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  args: ^2.2.0
  collection: ^1.17.0
  dbus: ^0.7.3
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  handy_window: ^0.3.0
  intl: ^0.18.0
  meta: ^1.7.0
  path: ^1.8.0
  safe_change_notifier: ^0.2.0
  stdlibc: ^0.1.0
  timezone_map:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/timezone_map
      ref: b193a7a8113c4c5400a9b58b42b1a104abd64bbb
  # TODO: move shared pages to a separate package
  ubuntu_desktop_installer:
    path: ../ubuntu_desktop_installer
  ubuntu_localizations: ^0.2.0
  ubuntu_logger: ^0.0.3
  ubuntu_service: ^0.2.0
  ubuntu_widgets:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_widgets
      ref: b193a7a8113c4c5400a9b58b42b1a104abd64bbb
  ubuntu_wizard:
    git:
      url: https://github.com/canonical/ubuntu-desktop-installer.git
      path: packages/ubuntu_wizard
  yaru: ^0.7.0
  yaru_icons: ^1.0.0
  yaru_widgets: ^2.4.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: 5.4.2
  ubuntu_test:
    path: ../ubuntu_test
  yaru_test: ^0.1.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
