name: Auto-merge

on:
  pull_request:
    branches:
      - main
      - 'ubuntu/**'
      - 'canary-*'

permissions:
  contents: write
  pull-requests: write

jobs:
  weblate:
    runs-on: ubuntu-latest
    if: ${{github.actor == 'weblate'}}
    steps:
      - name: Merge PR
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
