name: snap

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: snapcore/action-build@v1
      id: snapcraft
    - uses: actions/upload-artifact@v2
      if: github.event_name == 'workflow_dispatch'
      with:
        name: 'snap'
        path: ${{steps.snapcraft.outputs.snap}}
