name: Welcome

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.10.x'

jobs:
  snap:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - run: rm -r snap && ln -s packages/ubuntu_welcome/snap
    - uses: snapcore/action-build@v1
      id: snapcraft
    - uses: actions/upload-artifact@v3
      if: github.event_name == 'workflow_dispatch'
      with:
        name: 'snap'
        path: ${{steps.snapcraft.outputs.snap}}
